apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: uptime-kuma
  ports:
    - port: {{ .Values.kuma.servicePort }}
      targetPort: {{ .Values.kuma.port }}